### ISSUE TITLE
Trouble with ANSI Scalar Functions

### ISSUE THREAD

**Issue by v4x8182** [godmodelabs/flora-sql-parser#13]
I am getting quotes around CURRENT_TIMESTAMP in my where clause after converting a query to AST and back.  This is causing an invalid identifier error when executing the query.

**Comment by mbaumgartl** [comment]
Could you post the query, please?

**Comment by mbaumgartl** [comment]
Never mind!

CURRENT_TIMESTAMP is not supported by the parser at the moment. Because of the missing parentheses it is not identified as function.

**Comment by v4x8182** [comment]
Just for reference the following are ANSI Scalar functions that do not use parenthesis: CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP, CURRENT_USER, USER, SESSION_USER, SYSTEM_USER.  

Source: [http://users.atw.hu/sqlnut/sqlnut2-chp-4-sect-4.html](http://users.atw.hu/sqlnut/sqlnut2-chp-4-sect-4.html#sqlnut2-CHP-4-TABLE-3)

**Comment by mbaumgartl** [comment]
Fixed in [738bdf9f93cca](https://github.com/godmodelabs/flora-sql-parser/commit/738bdf9f93cca462ac611a1bd89d8ed042049cca).

**Comment by v4x8182** [comment]
This is great news!!  Do you know when you will publish a release with the latest changes?

**Comment by mbaumgartl** [comment]
We just released version 0.7.7 (which contains support scalar functions).
