### ISSUE TITLE
LIKE and IS NOT NULL

### ISSUE THREAD

**Issue by DivenireCode** [godmodelabs/flora-sql-parser#2]
it will throw error when i use LIKE and IS NOT NULL at the same time.
example: select * from tab where `username` like '%something%' and `img` is not null
throw error: SyntaxError: Expected [A-Za-z0-9_:] or [A-Za-z0-9_] but " " found.

**Comment by mbaumgartl** [comment]
IS NOT operator is not implemented in current version. We'll provide an update in a few days. Thanks for the bug report!

**Comment by mbaumgartl** [comment]
We published a new version.
