### ISSUE TITLE
Add support for date/time literals

### ISSUE THREAD

**Issue by jkerr5** [godmodelabs/flora-sql-parser#3]
Support date/time literals in the where clause:
```
DATE '1999-12-25' 
TIME '08:23:16' 
TIME '14:23:16.5' 
TIMESTAMP '1999-12-25 08:23:16' 
```
e.g.
```
SELECT * WHERE x = TIMESTAMP '1999-12-25 08:23:16' 
```

**Comment by mbaumgartl** [comment]
Fixed by [e69d089de7](https://github.com/godmodelabs/flora-sql-parser/commit/e69d089de7b55a3389ef9dacb6d4995cd38f1d53)
