### ISSUE TITLE
Missing build folder in v0.9.0

### ISSUE THREAD

**Issue by astorije** [godmodelabs/flora-sql-parser#30]
When upgrading to v0.9.0, we get:

```
ERROR in ./node_modules/flora-sql-parser/lib/parser.js
Module not found: Error: Can't resolve './../build/pegjs-parser'
```

Looking at https://unpkg.com/flora-sql-parser@0.8.1/ vs. https://unpkg.com/flora-sql-parser@0.9.0/, it seems that the `build` folder is missing.
Is that something that was forgotten at publish time?

**Comment by mbaumgartl** [comment]
Seems we had a problem with the build. Please use version 0.9.1. Sorry for the inconvenience.

**Comment by astorije** [comment]
No problem, thank you for the quick response!
