### ISSUE TITLE
v0.9.3 tag / release notes missing

### ISSUE THREAD

**Issue by astorije** [godmodelabs/flora-sql-parser#31]
https://www.npmjs.com/package/flora-sql-parser?activeTab=versions says there is a v0.9.3 version that has been published a couple days ago. [Releases](https://github.com/godmodelabs/flora-sql-parser/releases) do not show this version and the [latest commit](https://github.com/godmodelabs/flora-sql-parser/commit/abe092c4ea534720638275aac2add060d5bfe014) correspond to tagging to v0.9.2.
Was that accidental and v0.9.2 === v0.9.3, or was there an uncommitted change added to v0.9.3?

Thanks! 🙏

**Comment by not-implemented** [comment]
Oh sorry, seems I forgot to push 0.9.3 to GitHub. I'll do that tomorrow.

It is the same than 0.9.2 - I had a problem with the prepublish script (which generates the parser), so 0.9.2 was published to NPM without the compiled parser. As NPM does not allow to fix that in the same version, I had to increase the version number.

**Comment by astorije** [comment]
Ah, perfect, thank you! 🙏
KUTGW!

**Comment by not-implemented** [comment]
Pushed now :-)
