### ISSUE TITLE
Fails with columns named "type"

### ISSUE THREAD

**Issue by rgwozdz** [godmodelabs/flora-sql-parser#32]
I'm finding unexpected behavior if my column is name `type`:

```
const { Parser } = require("flora-sql-parser")
const parser = new Parser();
const ast = parser.parse("SELECT type FROM t");
```
Result in error:
`peg$SyntaxError: Expected [A-Za-z0-9_:] or [A-Za-z0-9_] but " " found.`

Changing the column name to something else, results in no error.  However, `type` is a fairly common property/column name.  I'm happy to try to PR this if someone can give me an indication where to start or any other hints.

*UPDATE*:  this works if you wrap `type` in double quotes.  Any thoughts about automating double quote wrapping for reserved words?

**Comment by mbaumgartl** [comment]
`type` is a reserved keyword in MySQL (which we us).

If you change your code to
```javascript
const { Parser } = require("flora-sql-parser")
const parser = new Parser();
const ast = parser.parse('SELECT "type" FROM t');
```
your query is parsed.

**Comment by rgwozdz** [comment]
@mbaumgartl thanks very much for your quick reply.  This makes sense.  If I knew all the problematic words, I could automate wrapping with double quotes.  I took a look at the [MySQL keywords/reserved word list](https://dev.mysql.com/doc/refman/8.0/en/keywords.html) but it seems that not all of them cause the error noted above:
```
const ast = parser.parse('SELECT ANALYZE FROM t');  // reserved word - no error
const ast = parser.parse('SELECT AGGREGATE FROM t'); // keyword - no error
```
Do you know what subset of MySQL keywords/reserved words will be problematic during parsing?

**Comment by mbaumgartl** [comment]
To be honest: I can't remember why I made `type` a reserved keyword in 6435f1eb :disappointed: 
We don't maintain a list of all reserved keywords in the parser (yet).

You can start with your unmodified, plain queries. If you have trouble parsing them, start quoting problematic attributes/columns. Unfortunately I don't have more advices. Parsing SQL is hard.

**Comment by rgwozdz** [comment]
> You can start with your unmodified, plain queries. If you have trouble parsing them, start quoting problematic attributes/columns. Unfortunately I don't have more advices. Parsing SQL is hard.

In my case, the parser is used on the fly to parse user input from web-clients.  For now, I'll start a list of words that need to be wrapped and add to it as they become known.
