### ISSUE TITLE
Delete query?

### ISSUE THREAD

**Issue by mmiller42** [godmodelabs/flora-sql-parser#33]
I'm having difficulty parsing a simple delete query. Is there something I'm doing wrong here?

```js
const { Parser } = require("flora-sql-parser")

new Parser().parse('delete from "user" where id = 1')
```

Output:

```
peg$SyntaxError: Expected "$", "(", "--", "/*", "INSERT", "REPLACE", "SELECT", "UPDATE", "WITH", "return", [ \t\n\r], or end of input but "d" found.
```

I have the example running [here on RunKit](https://runkit.com/mmiller42/5df69e3521d6b8001be31eb2).

**Comment by taozhi8833998** [comment]
[try it](https://runkit.com/taozhi8833998/5df6fe8f21d6b8001be36cb7)

**Comment by mmiller42** [comment]
Thanks!

What’s the difference between `parse` and `astify`? I wasn’t aware that there were more parser methods.

**Comment by taozhi8833998** [comment]
`parse` would return the `tables` and the `columns` that the SQL requested with the ast, while `astify` return the ast only. [read more](https://runkit.com/taozhi8833998/5df6fe8f21d6b8001be36cb7)
