### ISSUE TITLE
Potential issue on parsing SQL with escaped single quotes

### ISSUE THREAD

**Issue by haoliangyu** [godmodelabs/flora-sql-parser#34]
The parser has an issue parsing a statement with a string with escaped single quotes.

In PostgreSQL, the single quote in string can be escaped with an extra single quote before it. For example, this SQL works in PostgreSQL

``` sql
SELECT * FROM restaurants WHERE name = 'wendy''s'
```
but the parser throws an error for it

```
SyntaxError: Expected "!=", "%", "*", "+", "-", "--", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "AND", "GROUP", "HAVING", "LIMIT", "OR", "ORDER", "UNION", [ \t\n\r], or end of input but "'" found.
```

The workaround is to change the way of escaping from `''` to `\'`. So this SQL works in the parser

``` sql
SELECT * FROM restaurants WHERE name = 'wendy\'s'
```

**Comment by mbaumgartl** [comment]
Hi!

Thanks for reporting! :+1: 

253e698 should fix the problem.


Regards,
Marco
