### ISSUE TITLE
hope suport GROUP_CONCAT

### ISSUE THREAD

**Issue by DivenireCode** [godmodelabs/flora-sql-parser#36]
when i input 'GROUP_CONCAT' to parse AST it would throw error.
exp: 
  'SELECT GROUP_CONCAT(DISTINCT id) AS ids FROM t'
throw error: 
  message: 'Expected [A-Za-z0-9_:] or [A-Za-z0-9_] but " " found.',
    expected: [
      {
        type: 'class',
        parts: [Array],
        inverted: false,
        ignoreCase: false
      },
      {
        type: 'class',
        parts: [Array],
        inverted: false,
        ignoreCase: false
      },
      {
        type: 'class',
        parts: [Array],
        inverted: false,
        ignoreCase: false
      }
    ],
    found: ' ',
    location: {
      start: { offset: 28, line: 1, column: 29 },
      end: { offset: 29, line: 1, column: 30 }
    },
    name: 'SyntaxError'
  }

by the way
how can i do if i want to add a new expression parsing rule with plugin-ins

**Comment by mbaumgartl** [comment]
I just pushed 1c7f20f621 which brings support for DISTINCT in aggregate functions.

> how can i do if i want to add a new expression parsing rule with plugin-ins

This is not possible at the moment. The parser is generated from a grammar file. So we cannot add new expressions on the fly.

What are you missing?

**Comment by DivenireCode** [comment]
> I just pushed [1c7f20f](https://github.com/godmodelabs/flora-sql-parser/commit/1c7f20f62134af5e70a04cc187d768e13b692cf7) which brings support for DISTINCT in aggregate functions.

It worked! thx.

> This is not possible at the moment. The parser is generated from a grammar file. So we cannot add new expressions on the fly.

got it. I noticed that you depend on pegjs.
