### ISSUE TITLE
Error parsing table with database name

### ISSUE THREAD

**Issue by enex** [godmodelabs/flora-sql-parser#4]
The parser is able to parse `SELECT * FROM db.table` just fine, but it fails to parse `SELECT * FROM db."table"` and `SELECT * FROM "db"."table"` properly. It fails with the error message `Expected "--", "/*", [ \t\n\r], or [A-Za-z_] but "\"" found.`

**Comment by nicokaiser** [comment]
Thanks @enex for your issue report, we are looking into that.

**Comment by nicokaiser** [comment]
This is fixed in 879aff2 (version 0.7.4)
