### ISSUE TITLE
Single quote in values do not work

### ISSUE THREAD

**Issue by HuanxinHu** [godmodelabs/flora-sql-parser#6]
In version 0.7.4,  How to parse string when there is single quote?
For example:
parser.parse("select * from t where firstName=Hu's") 
parser.parse("select * from t where firstName=Hu\\'s")
both are not working.

**Comment by nicokaiser** [comment]
You need to escape the string you are comparing with:

```
parser.parse("select * from t where firstName='Hu\\'s'");
parser.parse('select * from t where firstName="Hu\'s"');
```

In the first line, the quote must be double escaped because otherwise it would end up in the string as unescaped and SQL would treat it as end quote.
