### ISSUE TITLE
Single quotes in column alias

### ISSUE THREAD

**Issue by patrickofriel-wk** [godmodelabs/flora-sql-parser#7]
First, wanted to say thanks for the great library, it's been very useful!

I've run into a problem when converting an ast selected column like this:
```
{
	expr: {
		type: ‘column_ref’,
		table: ‘tableid’,
		column: ‘columnname’
	},
	as: ‘column alias’
}
```
Where it'll be translated as a sql string to something like: 
`SELECT "tableid"."columnname" as 'column alias' from "tableid"`

When sending that string to execute with PRESTO I get an error like:

`No viable alternative at input 'column alias'`

This is because PRESTO expects double quotes instead of single quotes for column aliases. Would y'all mind if I create a pull request to change https://github.com/godmodelabs/flora-sql-parser/blob/master/lib/sql.js#L143 to use double quotes instead of single quotes?

Thanks again!

**Comment by patrickofriel-wk** [comment]
Added the pull request here https://github.com/godmodelabs/flora-sql-parser/pull/8 in case you wanted to take a look

**Comment by mbaumgartl** [comment]
Thank you very much for your pull request!
